name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: iliusa77/docker-getting-started:latest
    - name: Connect to Vagrant and execute uname
      run: |
         echo ${{ secrets.SSH_PRIVATE_KEY }} > key
         chmod 400 key 
         ssh vagrant@2.tcp.eu.ngrok.io -p 18472 -i key "uname"
         ssh vagrant@2.tcp.eu.ngrok.io -p 18472 -i key "uptime"
      shell: bash
